[toolchain]

[features]
resolution = true
skip-lint = false

# [programs.localnet]
# contract = "EenrikujwYRzq3a814cKEp2WzVUSag2QAbEiwvVPEHsX"

[registry]
url = "https://api.apr.dev"

[programs.devnet]
swap_example = "AsGVFxWqEn8icRBFQApxJe68x3r9zvfSbmiEzYFATGYn"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
